{{- if .Values.images.backend.replicaCount }}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: "{{ template "fullname" . }}-backend"
    labels:
        app: {{ template "name" . }}
        chart: {{ template "chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: "backend"
spec:
    replicas: {{ .Values.images.backend.replicaCount }}
    selector:
        matchLabels:
            app: {{ template "name" . }}
            release: {{ .Release.Name }}
            component: "backend"
    template:
        metadata:
            labels:
                app: {{ template "name" . }}
                release: {{ .Release.Name }}
                component: "backend"
        spec:
            containers:
                -   name: "{{ .Chart.Name }}-backend"
                    image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag | default .Chart.Version }}"
                    imagePullPolicy: "{{ .Values.pullPolicy }}"
                    ports:
                        -   containerPort: 5080
                            name: http
                        -   containerPort: 5081
                            name: actuator
                        -   containerPort: 5025
                            name: smtp
                      {{- if or .Values.images.backend.debug .Values.images.backend.debugsuspend }}
                        -   containerPort: 5005
                            name: "jvm-debug"
                      {{- end }}
                    env:
                        -   name: JAVA_OPTS
                            value: "{{ .Values.images.backend.javaOpts }}{{ if .Values.images.backend.debug }} -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005{{ end }}{{ if .Values.images.backend.debugsuspend }} -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005{{ end }}"
                      {{- range $key, $value := .Values.images.backend.env }}
                        -   name: "{{ $key }}"
                            value: "{{ $value }}"
                      {{- end }}
                    resources:
                        requests:
                            memory: {{ .Values.images.backend.memoryRequest | quote }}
                          {{- if .Values.images.backend.cpuRequest }}
                            cpu: {{ .Values.images.backend.cpuRequest | quote }}
                          {{- end }}
                        limits:
                            memory: {{ .Values.images.backend.memoryLimit | quote }}
                          {{- if .Values.images.backend.cpuLimit }}
                            cpu: {{ .Values.images.backend.cpuLimit | quote }}
                          {{- end }}
                    {{- if .Values.images.backend.readiness }}
                    readinessProbe:
                        httpGet:
                            path: /actuator/health
                            port: 5081
                        initialDelaySeconds: 20
                        periodSeconds: 10
                        timeoutSeconds: 5
                        successThreshold: 2
                        failureThreshold: 3
                    {{- end }}
                    {{- if .Values.images.backend.liveness }}
                    livenessProbe:
                        httpGet:
                            path: /actuator/health
                            port: 5081
                        initialDelaySeconds: 300
                        periodSeconds: 30
                        timeoutSeconds: 8
                        successThreshold: 1
                        failureThreshold: 3
                    {{- end }}
            imagePullSecrets:
                -   name: regsecret
  {{- end }}
